version: 0.2

env:
  #variables:
     # key: "value"
     # key: "value"
  parameter-store:
     DOCKER_USERNAME: /docker/username
     DOCKER_PASSWORD: /docker/password
     DOCKER_URL: /docker/url
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  install:
    runtime-versions:
       python: 3.11
      # name: version
    #commands:
      # - command
      # - command
  pre_build:
    commands:
      - pip install -r requirements.txt
      # - command
  build:
    commands:
       
       - echo "Building docker image"
       - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_URL"
       - docker build -t "$DOCKER_URL/$DOCKER_USERNAME/aws-codebuild:latest" . -f Dockerfile.txt
       - docker push docker.io/sahitya19/aws-codebuild:latest
  post_build:
    commands:
       - echo "Build is successful"
      # - command
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
# - paths
